sudo: required
services:
    - docker

before_script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: 
    - docker run -v $(pwd):/root --rm -t openfaas/faas-cli:0.8.14 faas-cli template pull https://github.com/burtonr/csharp-kestrel-template
    - docker run -v $(pwd):/root --rm -t openfaas/faas-cli:08.14 faas-cli build -f bikeshare-function.yml 

after_success:
    - docker run -v $(pwd):/root --rm -t openfaas/faas-cli:08.14 faas-cli push -f bikeshare-function.yml 
