sudo: required
services:
    - docker
before_script:
    - curl -sLS https://cli.openfaas.com | sudo sh
script: 
    - faas-cli template pull https://github.com/burtonr/csharp-kestrel-template
    - faas-cli build -f bikeshare-function.yml
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; faas-cli push -f bikeshare-function.yml