name: CI
on: [push, pull_request]
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
        
      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template pull ${{ github.token }}/github.com/burtonr/csharp-kestrel-templategolang-http
      
      - name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f bikeshare-function.yml --shrinkwrap