name: CI
on: [push, pull_request]
jobs:
  BikeshareFunction-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
        
      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template pull https://github.com/burtonr/csharp-kestrel-template
      
      - name: Run build --shrinkwrap
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f bikeshare-function.yml --shrinkwrap

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build bikeshare-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/bikeshare-function/
          file: ./build/bikeshare-function/Dockerfile
          push: false
          tags: andmos/bikeshare-function:${{ steps.define_env.outputs.github-sha-short }}

      - name: Build bikeshare-slack-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/bikeshare-slack-function/
          file: build/bikeshare-slack-function/Dockerfile
          push: false
          tags: andmos/bikeshare-slack-function:${{ steps.define_env.outputs.github-sha-short }}

      - name: Build gbfs-systems-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/gbfs-systems-function/
          file: ./build/gbfs-systems-function/Dockerfile
          push: false
          tags: andmos/gbfs-systems-function:${{ steps.define_env.outputs.github-sha-short }}