name: CI
on:
  push:
    branches: 
      - master
jobs:
  BikeshareFunction-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define ENV VARS
        id: define_env
        run:  echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
        
      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template pull https://github.com/burtonr/csharp-kestrel-template
      
      - name: Run build --shrinkwrap
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f bikeshare-function.yml --shrinkwrap

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push bikeshare-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/bikeshare-function/
          file: ./build/bikeshare-function/Dockerfile
          push: true
          tags: andmos/bikeshare-function:latest

      - name: Build and push bikeshare-slack-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/bikeshare-slack-function/
          file: build/bikeshare-slack-function/Dockerfile
          push: true
          tags: andmos/bikeshare-slack-function:latest

      - name: Build and push gbfs-systems-function OpenFaaS functions
        uses: docker/build-push-action@v2
        with:
          context: ./build/gbfs-systems-function/
          file: ./build/gbfs-systems-function/Dockerfile
          push: true
          tags: andmos/gbfs-systems-function:latest